repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
-   repo: https://github.com/seddonym/import-linter
    rev: v1.9.0
    hooks:
    - id: import-linter
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
    - id: pycln
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    - id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
