name: Terragrunt Apply Dev

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT: 203918846720
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::203918846720:role/mightystingbee-101digital-assignment-terraform-role
  RESOURCE_PREFIX: mightystingbee
  SERVICE_NAME: service-weather
  EKS_CLUSTER_NAME: mightystingbee-api
  REPOSITORY_ID: 203918846720.dkr.ecr.us-east-1.amazonaws.com/mightystingbee-ecr

jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      aws_account: ${{ env.AWS_ACCOUNT }}
      aws_region: ${{ env.AWS_REGION }}
      aws_assume_role: ${{ env.AWS_ROLE_ARN }}
      resource_prefix: ${{ env.RESOURCE_PREFIX }}
      service_name: ${{ env.SERVICE_NAME }}
      eks_cluster_name: ${{ env.EKS_CLUSTER_NAME }}

  terragrunt-apply-dev:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yaml
    needs:
      - build-and-push
    secrets: inherit
    with:
      environment: dev
