name: Terragrunt Apply Prod

on:
  push:
    tags:
      - releases-v*

env:
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE }}
  RESOURCE_PREFIX: ${{ vars.RESOURCE_PREFIX }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  REPOSITORY_ID: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ vars.RESOURCE_PREFIX }}-ecr

jobs:
  build-and-push-prod:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      environment: prod
      aws_account: ${{ vars.AWS_ACCOUNT_PROD }}
      aws_region: ${{ vars.AWS_REGION_PROD }}
      aws_assume_role: ${{ vars.AWS_ASSUME_ROLE_PROD }}
      resource_prefix: ${{ vars.RESOURCE_PREFIX_PROD }}
      service_name: ${{ vars.SERVICE_NAME_PROD }}
      eks_cluster_name: ${{ vars.EKS_CLUSTER_NAME_PROD }}

  terragrunt-apply-prod:
    permissions:
      id-token: write
      contents: read
    needs:
      - build-and-push-prod
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: prod
